version: "3.8"

services:
  # Frontdoor
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - APISIX_HOST
      - APISIX_PORT
      - DOMAIN
      - LE_EMAIL
      - LE_OPTIONS
      - LE_RENEW_OPTIONS
      - LE_RENEW_CRON_COMMAND
    env_file: .env
    depends_on:
      - apisix
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - dmz
    volumes:
      - reverse-proxy-nginx-data:/etc/letsencrypt
  apisix:
    build: 
      context: ./apisix
      dockerfile: Dockerfile
    environment:
      - APISIX_STAND_ALONE=true
    restart: unless-stopped
    networks:
      - app
      - dmz
    volumes:
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:rw
      - ./apisix/conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./apisix/conf/debug.yaml:/usr/local/apisix/conf/debug.yaml:ro
      - ./apisix/scripts/guid-verify.lua:/usr/local/apisix/scripts/guid-verify.lua

  # Application Database
  database:
    build: 
      context: ./app-database
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_RESTAURANT_USER
      - POSTGRES_RESTAURANT_PASSWORD
      - POSTGRES_RESTAURANT_DB
      - POSTGRES_ORDER_USER
      - POSTGRES_ORDER_PASSWORD
      - POSTGRES_ORDER_DB
      - POSTGRES_KITCHEN_USER
      - POSTGRES_KITCHEN_PASSWORD
      - POSTGRES_KITCHEN_DB
    env_file: .env
    networks:
      - app
    volumes:
      - db-datastore:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:5050"
    networks:
      - app
    restart: unless-stopped
  
  # Application Services
  restaurant:
    image: ghcr.io/table-side/restaurant:main
    depends_on:
      - database
    networks:
      - app
    restart: unless-stopped
  order:
    image: ghcr.io/table-side/order:main
    depends_on:
      - database
      - restaurant
    networks:
      - app
    restart: unless-stopped
  kitchen:
    image: ghcr.io/table-side/kitchen:main
    depends_on:
      - database
      - restaurant
      - order
    networks:
      - app
    restart: unless-stopped

volumes:
  reverse-proxy-nginx-data:
  db-datastore:

networks:
  dmz:
    driver: bridge
  app:
    driver: bridge
  