version: "3.8"

services:
  database:
    image: ghcr.io/table-side/database:main
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file: .env
    networks:
      - application

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    env_file: .env
    networks:
      - application
      - public
  
  frontdoor:
    image: ghcr.io/table-side/frontdoor:main
    depends_on:
      - database
    networks:
      - application
      - public

  restaurant:
    image: ghcr.io/table-side/restaurant:main
    depends_on:
      - database
      - frontdoor
    networks:
      - application

  order:
    image: ghcr.io/table-side/order:main
    depends_on:
      - database
      - restaurant
    networks:
      - application

  kitchen:
    image: ghcr.io/table-side/kitchen:main
    depends_on:
      - database
      - restaurant
      - order
    networks:
      - application

networks:
  application:
    driver: overlay
  public:
    driver: host
    external: true
  