version: "3.8"

services:
  database:
    image: ghcr.io/table-side/database:main
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_FRONTDOOR_USER
      - POSTGRES_FRONTDOOR_PASSWORD
      - POSTGRES_FRONTDOOR_DB
      - POSTGRES_KITCHEN_USER
      - POSTGRES_KITCHEN_PASSWORD
      - POSTGRES_KITCHEN_DB
      - POSTGRES_ORDER_USER
      - POSTGRES_ORDER_PASSWORD
      - POSTGRES_ORDER_DB
      - POSTGRES_RESTAURANT_USER
      - POSTGRES_RESTAURANT_PASSWORD
      - POSTGRES_RESTAURANT_DB
    env_file: .env
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    env_file: .env
    networks:
      - internal
      - external
    ports:
      - "8001:80"
  
  frontdoor:
    image: ghcr.io/table-side/frontdoor:main
    depends_on:
      - database
    networks:
      - internal
      - external
    ports:
      - "8000:3000"

  restaurant:
    image: ghcr.io/table-side/restaurant:main
    depends_on:
      - database
      - frontdoor
    networks:
      - internal

  order:
    image: ghcr.io/table-side/order:main
    depends_on:
      - database
      - restaurant
    networks:
      - internal

  kitchen:
    image: ghcr.io/table-side/kitchen:main
    depends_on:
      - database
      - restaurant
      - order
    networks:
      - internal

networks:
  external:
    driver: overlay
    attachable: true
  internal:
    driver: overlay
    internal: true
    attachable: true
  