version: "3.8"

services:
  etcd:
    image: bitnami/etcd:latest
    restart: always
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix
    volumes:
      - etcd_data:/bitnami/etcd

  apisix:
    image: apache/apisix:latest
    restart: always
    depends_on:
      - etcd
    networks:
      - app-network
      - apisix
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./conf/apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro

  apisix-dashboard:
    image: apache/apisix-dashboard:latest
    restart: on-failure
    depends_on:
      - etcd
      - apisix
    networks:
      - apisix
    ports:
      - "9180:9180"
    volumes:
      - ./conf/apisix-dashboard/config.yml:/usr/local/apisix-dashboard/conf/conf.yaml
    
  database:
    image: ghcr.io/table-side/database:main
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_IAM_USER
      - POSTGRES_IAM_PASSWORD
      - POSTGRES_IAM_DB
      - POSTGRES_KITCHEN_USER
      - POSTGRES_KITCHEN_PASSWORD
      - POSTGRES_KITCHEN_DB
      - POSTGRES_ORDER_USER
      - POSTGRES_ORDER_PASSWORD
      - POSTGRES_ORDER_DB
      - POSTGRES_RESTAURANT_USER
      - POSTGRES_RESTAURANT_PASSWORD
      - POSTGRES_RESTAURANT_DB
    env_file: .env
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    env_file: .env
    networks:
      - app-network
      - external
    ports:
      - "8001:80"
  
  iam:
    image: ghcr.io/table-side/iam:main
    depends_on:
      - database
    networks:
      - app-network

  restaurant:
    image: ghcr.io/table-side/restaurant:main
    depends_on:
      - database
      - iam
    networks:
      - app-network

  order:
    image: ghcr.io/table-side/order:main
    depends_on:
      - database
      - restaurant
    networks:
      - app-network

  kitchen:
    image: ghcr.io/table-side/kitchen:main
    depends_on:
      - database
      - restaurant
      - order
    networks:
      - app-network

volumes:
  etcd_data:
    driver: local

networks:
  apisix:
    driver: bridge
  external:
    driver: overlay
    attachable: true
  app-network:
    driver: overlay
    internal: true
    attachable: true
  