apisix:
  node_listen: 9080
  enable_ipv6: false

deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0 # allow all (TODO: change to specific IP)

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin

  etcd:
    host:
      - "http://etcd:2379"
    prefix: "/apisix"
    timeout: 30

plugins:
  key-auth:
    key_names:
      - "JWT_SECRET"
    hide_credentials: true
  jwt:
    secret: "$ENV://JWT_SECRET"
    algorithms: ["HS256"]
    # ca_cert_file: "/etc/apisix/cert/jwt/ca.crt" # todo: add this file

routes:
  - name: iam-auth-routes # no auth required
    uri:
      - /auth/*
    upstream:
      type: roundrobin
      nodes:
        - iam:3000

  - name: iam-user-profile-routes # auth required
    uri:
      - /users/*
    upstream:
      type: roundrobin
      nodes:
        - iam:3000
    plugins:
      jwt-auth:

  - name: restaurant-all-route # no auth required
    uri:
      - /restaurants/all
    method:
      - GET
    upstream:
      type: roundrobin
      nodes:
        - restaurant:3000/all/

  - name: restaurant-id-get-route # no auth required, guid verification required
    uri:
      - /restaurants/:guid/details
    method:
      - GET
    script: "../../apisix/scripts/guid-verify.lua"
    upstream:
      type: roundrobin
      nodes:
        - restaurant:3000/:guid/details/

  - name: restaurant-protected-routes # auth required
    uri:
      - /restaurants/*
    upstream:
      type: roundrobin
      nodes:
        - restaurant:3000/
  
  - name: order-routes # auth required
    uri:
      - /orders/*
    upstream:
      type: roundrobin
      nodes:
        - order:3000/
  
  - name: kitchen-routes # auth required
    uri:
      - /kitchen/*
    upstream:
      type: roundrobin
 `     nodes:
        - kitchen:3000/
